description: MSFT2020Boosting_FSOD

target:
  service: amlk8s
  name: itphyperdellcl1
  vc: resrchvc

environment:
  image: tmlabonte/wsod_transfer:latest
 
code:
  local_dir: $CONFIG_DIR/

storage:
  cvgroupsouthcentral:
    storage_account_name: cvgroupsouthcentral
    container_name: datasets

jobs:
- name: MSFT2020Boosting_FSOD
  sku: G4
  command:
  - python -m torch.distributed.launch --nproc_per_node=4 tools/train_net.py --config-file wsod/fsod800_to_fsod200/ocud_it0.yaml && python -m torch.distributed.launch --nproc_per_node=4 tools/train_net.py --config-file wsod/fsod800_to_fsod200/mil_it0.yaml
