description: MSFT2020Boosting_FSOD

target:
  service: aml
  name: itphyperdellcl1
  vc: msrhyper
  
environment:
  image: joshins/pytorch:1.7.0-cuda11.0-cudnn8-devel-maskrcnn-benchmark-v2
  setup:
  - pip install numpy==1.21.0
  
code:
  local_dir: $CONFIG_DIR/

storage:
  cvgroupsouthcentral:
    storage_account_name: cvgroupsouthcentral
    container_name: datasets

jobs:
- name: MSFT2020Boosting_FSOD
  sku: G4
  command:
  - python -m torch.distributed.launch --nproc_per_node=4 tools/train_net.py --config-file wsod/fsod800_to_fsod200/ocud_it0.yaml
