description: MSFT2020Boosting_iNaturalist

target:
  service: amlk8s
  name: itphyperdgx2cl2
  vc: hcrr06
  
environment:
  image: tmlabonte/wsod_transfer:latest
  setup:
  - pip install numpy==1.21.0
  
code:
  local_dir: $CONFIG_DIR/

storage:
  cvgroupsouthcentral:
    storage_account_name: cvgroupsouthcentral
    container_name: datasets

jobs:
- name: MSFT2020Boosting_FSOD_Split0
  sku: G16
  command:
  - python -m torch.distributed.launch --nproc_per_node=16 tools/train_net.py --config-file wsod/fsod800_to_fsod200/inaturalist/mil_it0.yaml
