description: MSFT2020Boosting_FSOD

target:
  service: amlk8s
  name: itpseasiav100cl
  vc: resrchvc
  
environment:
  image: tmlabonte/wsod_transfer:latest
  setup:
  - pip install numpy==1.21.0
  - pip install sparsemax
  
code:
  local_dir: $CONFIG_DIR/

storage:
  cvgroupsouthcentral:
    storage_account_name: cvgroupsouthcentral
    container_name: datasets

jobs:
- name: MSFT2020Boosting_FSOD_Split0
  sku: G4
  command:
  - python -m torch.distributed.launch --nproc_per_node=4 tools/train_net.py --config-file wsod/fsod800_to_fsod200/split0/mil_it0.yaml

- name: MSFT2020Boosting_FSOD_Split1
  sku: G4
  command:
  - python -m torch.distributed.launch --nproc_per_node=4 tools/train_net.py --config-file wsod/fsod800_to_fsod200/split1/mil_it0.yaml

- name: MSFT2020Boosting_FSOD_Split2
  sku: G4
  command:
  - python -m torch.distributed.launch --nproc_per_node=4 tools/train_net.py --config-file wsod/fsod800_to_fsod200/split2/mil_it0.yaml

- name: MSFT2020Boosting_FGVC
  sku: G4
  command:
  - python -m torch.distributed.launch --nproc_per_node=4 tools/train_net.py --config-file wsod/fsod800_to_fsod200/fgvc/mil_it0.yaml
